chore(RHTAPWATCH-361): simple Splunk test
redhat-appstudio/segment-bridge pull request #31
Opened 2023-08-06 12:30 UTC by Omeramsc

A test on a Splunk query to demonstrate GO test-framework. It's running the fake cluster and checks that the count of logs indexed for the test_index is as we expect.

depends on #20

2023-08-06 12:40 UTC, yftacherzog commented on splunk/splunk.go
> +	searchQuery := "search=" + (fmt.Sprintf("search index=%s | stats count", index))
Do we need the outer parentheses here?

2023-08-06 12:49 UTC, Omeramsc commented on splunk/splunk.go
> +	searchQuery := "search=" + (fmt.Sprintf("search index=%s | stats count", index))
Nope, good catch.

2023-08-06 12:54 UTC, yftacherzog approved these changes

2023-08-07 06:30 UTC, ifireball requested changes
Not looking at the code here yet, I think this can be a part of #20, so that well have some tests included for the code there.

2023-08-07 06:50 UTC, Omeramsc commented
@b

> Not looking at the code here yet, I think this can be a part of #20, so that well have some tests included for the code there.

I get the value of having the tests with the framework, but I separated them on purpose. #20 is big enough and other changes depends on it, adding GO test code (which may need multiple changes) will prolong it even further.

2023-08-07 07:06 UTC, ifireball commented
> > Not looking at the code here yet, I think this can be a part of #20, so that well have some tests included for the code there.
> 
> I get the value of having the tests with the framework, but I separated them on purpose. #20 is big enough and other changes depends on it, adding GO test code (which may need multiple changes) will prolong it even further.

Are we cheating ourselves? You can't reliably merge that code without having this code - there are both parts of the same work - if you really need so separation use different commits within the same PR.

2023-08-14 14:38 UTC, closed without merging