chore(RHTAPWATCH-160) Run SAST checks for each opened PR
redhat-appstudio/segment-bridge pull request #82
Opened 2023-10-25 18:39 UTC by Kousalya1998

# Description

- Run SAST checks for each opened PR

## Issue ticket number and link
[RHTAPWATCH-160](https://issues.redhat.com/browse/RHTAPWATCH-160)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

# Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added meaningful description with JIRA/GitHub issue key (if applicable)
- [ ] I have updated labels (if needed)

2023-10-25 19:46 UTC, hmariset reviewed
new line missing at end of file

2023-10-26 11:42 UTC, Omeramsc commented on .pre-commit-config.yaml
> +    rev: v1.32.0
Is this required for the SAST checks? if not, omit it from this commit.

2023-10-31 08:31 UTC, ifireball commented
please rebase and resolve conflicts

2023-10-31 16:13 UTC, Omeramsc commented
@Kousalya1998 it seems like the pre-commit checks are not running\stuck. 
also you should resolve the conflict with the `pre-commit-config` file, it may help.

2023-11-01 08:59 UTC, Omeramsc commented on .pre-commit-config.yaml
> +    repo: https://github.com/fabasoad/pre-commit-snyk
Missing `rev` key.

2023-11-01 09:21 UTC, ifireball requested changes

2023-11-01 14:05 UTC, Kousalya1998 commented
@Omeramsc I resolved the conflicts but the CI keeps failing

2023-11-01 14:13 UTC, yftacherzog commented
> @Omeramsc I resolved the conflicts but the CI keeps failing

one failure is gitlint. You need to fix the commit message (missing colon after the closing brackets)

2023-11-01 14:15 UTC, Kousalya1998 commented
> > @Omeramsc I resolved the conflicts but the CI keeps failing
> 
> one failure is gitlint. You need to fix the commit message (missing colon after the closing brackets)

Updated. Thanks.

2023-11-01 14:17 UTC, yftacherzog commented
> > @Omeramsc I resolved the conflicts but the CI keeps failing
> 
> one failure is gitlint. You need to fix the commit message (missing colon after the closing brackets)

The second one is about the revision. It tells which release of the pluging repo should be taken. You need to open the URL mentioned under `repo` and on the right you'd see `Releases`. You need to take the latest one from there. The one you have at the moment does not exist.

2023-11-01 14:30 UTC, Kousalya1998 commented
> > > @Omeramsc I resolved the conflicts but the CI keeps failing
> > 
> > 
> > one failure is gitlint. You need to fix the commit message (missing colon after the closing brackets)
> 
> The second one is about the revision. It tells which release of the plugin repo should be taken. You need to open the URL mentioned under `repo` and on the right you'd see `Releases`. You need to take the latest one from there. The one you have at the moment does not exist.

Okay added v0.5.0

2023-11-01 14:38 UTC, yftacherzog commented
@Kousalya1998 still need to fix multiple CI failures.

2023-11-06 08:44 UTC, Omeramsc requested changes
```
go-sec-mod...............................................................Failed
- hook id: go-sec-mod
- duration: 0.01s
- exit code: 1

error: command not found: gosec
```

seems like this check still fails

2023-11-08 17:20 UTC, Kousalya1998 commented
/retest

2023-11-08 18:21 UTC, Kousalya1998 commented
> ```
> go-sec-mod...............................................................Failed
> - hook id: go-sec-mod
> - duration: 0.01s
> - exit code: 1
> 
> error: command not found: gosec
> ```
> 
> seems like this check still fails

Updated the code. Ignore this version.

2023-11-08 18:21 UTC, Kousalya1998 commented
> ```
> go-sec-mod...............................................................Failed
> - hook id: go-sec-mod
> - duration: 0.01s
> - exit code: 1
> 
> error: command not found: gosec
> ```
> 
> seems like this check still fails

snyk check passes now.

2023-11-08 21:23 UTC, Kousalya1998 commented
@Omeramsc @hmariset @amisstea Need your reviews.

2023-11-09 11:53 UTC, Omeramsc approved these changes
LGTM

2023-11-09 13:31 UTC, hmariset approved these changes
LGTM

2023-11-13 08:24 UTC, ifireball commented
@Kousalya1998 assuming the SASK task image version is being updated by renovatebot like the other images in the pipeline to we really still need this PR?

2023-11-13 21:22 UTC, Kousalya1998 commented
> assuming the SASK task image version is being updated by renovatebot like the other images in the pipeline do we really still need this PR?

As far as I can tell, the SAST check passed now and that was the requirement for this task. I am not sure about renovatebot..

2023-11-23 10:09 UTC, Omeramsc commented
Where does this change stands? Are we planning to use it?
(If so, please rebase and solve conflicts)

2023-11-28 14:29 UTC, amisstea approved these changes
I don't see why we shouldn't merge this. The `.snyk` file seems necessary and renovatebot hasn't updated these container image refs for whatever reason.

2023-11-28 14:29 UTC, amisstea commented on .tekton/segment-bridge-pull-request.yaml
> +          value:  quay.io/redhat-appstudio-tekton-catalog/task-sast-snyk-check:0.1@sha256:edd4ba638b71de52c2662abd3e93fd876e6e75cd07b162d13fae014d3a1a1fac
Please remove leading spaces.

2023-11-28 17:21 UTC, Kousalya1998 commented on .tekton/segment-bridge-pull-request.yaml
> +          value:  quay.io/redhat-appstudio-tekton-catalog/task-sast-snyk-check:0.1@sha256:edd4ba638b71de52c2662abd3e93fd876e6e75cd07b162d13fae014d3a1a1fac
Removed.

2023-11-28 20:02 UTC, Kousalya1998 commented
/retest

2023-11-30 19:14 UTC, Kousalya1998 commented
/retest

2023-11-30 20:20 UTC, Kousalya1998 commented
/retest

2023-12-07 08:07 UTC, ifireball commented
I can see the SNYK check is running now:

![Screenshot from 2023-12-07 10-04-12](https://github.com/redhat-appstudio/segment-bridge/assets/918532/7acf0a7f-7e6c-498e-8362-cbd9cd27d658)

But its failing with these errors in the logs:
```
[sast-snyk-check] sast-snyk-check test failed because of the following issues:
[sast-snyk-check] Snyk Code is not supported for org: enable in Settings > Snyk Code
[sast-snyk-check] {"result":"ERROR","timestamp":"1701929575","note":"Task sast-snyk-check failed: For details, check Tekton task log.","namespace":"default","successes":0,"failures":0,"warnings":0}
```

What will it take to make it pass?

2023-12-13 14:27 UTC, Kousalya1998 commented
> I can see the SNYK check is running now:
> 
> ![Screenshot from 2023-12-07 10-04-12](https://private-user-images.githubusercontent.com/918532/288680021-7acf0a7f-7e6c-498e-8362-cbd9cd27d658.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Nzc4NjUsIm5iZiI6MTcwMjQ3NzU2NSwicGF0aCI6Ii85MTg1MzIvMjg4NjgwMDIxLTdhY2YwYTdmLTdlNmMtNDk4ZS04MzYyLWNiZDljZDI3ZDY1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxNDI2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmE1NjBiZGQ2YmRlYWRmNjViZjllNGUzMjBkOWFiNjRiNDI2Y2Q2MDY4MzczZDU5ZGExMGNkNWRkOWVlM2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fPNWuOccfpl4av5gbyNMCRls52GSnXERIyEngHdGkG4)
> 
> But its failing with these errors in the logs:
> 
> ```
> [sast-snyk-check] sast-snyk-check test failed because of the following issues:
> [sast-snyk-check] Snyk Code is not supported for org: enable in Settings > Snyk Code
> [sast-snyk-check] {"result":"ERROR","timestamp":"1701929575","note":"Task sast-snyk-check failed: For details, check Tekton task log.","namespace":"default","successes":0,"failures":0,"warnings":0}
> ```
> 
> What will it take to make it pass?

@ifireball I saw that too. So, to make it `SUCCESS` we need that Snyk subscription account. I am trying to get that access. It throws an error because I used a free trial version.

2023-12-13 15:08 UTC, Kousalya1998 commented
/retest

2023-12-13 18:12 UTC, Kousalya1998 commented
/retest

2023-12-13 18:27 UTC, Kousalya1998 commented
@ifireball @amisstea I FINALLY  got the Red Hat SSO access to the SNYK tool!! updated the secrets. However, it still gives the ERROR message. Something else is wrong now. Checking on that with the `#rhtap developers` channel.
![image](https://github.com/redhat-appstudio/segment-bridge/assets/113047440/30e04a4c-e0be-4dd3-b8ec-b0d6819f9cf6)

2023-12-13 19:13 UTC, Kousalya1998 commented
/retest

2023-12-13 21:02 UTC, Kousalya1998 commented
/retest

2023-12-13 21:03 UTC, Kousalya1998 commented
/retest

2023-12-14 18:01 UTC, Kousalya1998 commented
/retrigger

2023-12-14 18:22 UTC, Kousalya1998 commented
Similar issues have arisen with the 'service-provider integrator' team, who have claimed they merged the PR without any issues even after the FAILURE message. Testing it.
https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1702020501097879

2023-12-14 18:31 UTC, Kousalya1998 commented
/retest

2023-12-15 21:42 UTC, Kousalya1998 commented
/rebuild

2023-12-18 22:37 UTC, Kousalya1998 commented
@ifireball I had a meeting with Scott Hebert today and we came across an image that we are using in the segment-bridge's Dockerfile:
```
# Second stage: Create the final container image
FROM registry.redhat.io/openshift4/ose-tools-rhel8:v4.13.0-202311211131.p0.gc7c6eb2.assembly.stream
```

Also, I see that tools for [Red Hat appstudio's Dockerfile ](https://github.com/redhat-appstudio/tools/blob/main/Dockerfile) use a different image which looks like:
```
RUN \
    curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.12.36/openshift-client-linux.tar.gz \
    | tar -C /opt/app-root/bin/ -xvzf - oc \
    && /usr/libexec/s2i/assemble
```
I guess the image that we are using causes HIGH vulnerability and that is making the SAST check Fail. However, with the tools repo if you see the SAST check passes with a different image:
![image](https://github.com/redhat-appstudio/segment-bridge/assets/113047440/c5419b09-7fcd-40bd-b7fa-d9a90c71ed02)

2023-12-19 13:10 UTC, ifireball commented
> @ifireball I had a meeting with Scott Hebert today and we came across an image that we are using in the segment-bridge's Dockerfile:
> 
> ```
> # Second stage: Create the final container image
> FROM registry.redhat.io/openshift4/ose-tools-rhel8:v4.13.0-202311211131.p0.gc7c6eb2.assembly.stream
> ```
> 
> Also, I see that tools for [Red Hat appstudio's Dockerfile ](https://github.com/redhat-appstudio/tools/blob/main/Dockerfile) using a different image which looks like:
> 
> ```
> RUN \
>     curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.12.36/openshift-client-linux.tar.gz \
>     | tar -C /opt/app-root/bin/ -xvzf - oc \
>     && /usr/libexec/s2i/assemble
> ```
> 
> I guess the image that we are using causes HIGH vulnerability and that is making the SAST check Fail. However, with the tools repo if you see the SAST check passes with a different image: ![image](https://private-user-images.githubusercontent.com/113047440/291425551-c5419b09-7fcd-40bd-b7fa-d9a90c71ed02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5OTExNzUsIm5iZiI6MTcwMjk5MDg3NSwicGF0aCI6Ii8xMTMwNDc0NDAvMjkxNDI1NTUxLWM1NDE5YjA5LTdmY2QtNDBiZC1iN2ZhLWQ5YTkwYzcxZWQwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMzAxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzMxZTlkN2YzMjJmMDdhMWFhM2JlODFlZTBiZmFmM2MzYmYzNjMwZjUyZjQ5MDQ1ODc2NjNjYmQ0NjYzYWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hopW1XU60o2s2HU6dno3HXXZZOSp59Zp933LvlfUhjo)

I think the issues Scott talked about have to do with the Clair scan and not the SAST scan. From looking at the logs it seems the SAST scan is failing on issues in the `kwok/host-operator` directory which is a Git submodule linking to the [host-operator](https://github.com/codeready-toolchain/host-operator) repo that we don't own. We can't do much about SAST issue in it.

If the SAST scan is running and failing on actual security issues v.s. system/invocation issues we can regard this task as successful.

2023-12-20 06:15 UTC, ifireball requested changes

2023-12-20 15:20 UTC, Kousalya1998 commented on .snyk
> +  global:
Got it. reverted the changed and added it under exclude

2023-12-21 14:16 UTC, Kousalya1998 commented on .tekton/segment-bridge-pull-request.yaml
> +          value: quay.io/redhat-appstudio-tekton-catalog/task-buildah:0.1@sha256:9e7be6d3f2cde33fabfda9d454757530ce7f73e2414c00da1a3ebabf95fc52c5
reverted the changes I made to the images. Still gives some errors

2024-01-04 15:23 UTC, klakshma21 commented
Due to losing access to my current GitHub account, I am closing this PR and opening a new one
https://github.com/redhat-appstudio/segment-bridge/pull/147

2024-01-07 07:52 UTC, Omeramsc commented
Closing as a new PR opened instead.

2024-01-07 07:52 UTC, closed without merging